name: Motivation & Personal Development
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/926f16c3-baf6-4569-b2d2-a2fbd140b05c.png
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/de020ac7-2fe6-4d40-ae86-1204981717c6.png
layout_spectrum: 0.24072570168643748
typography_spectrum: 0.571933125991116
analytics:
  google: UA-79126334-1
color:
  brandColors:
    - '#000000'
    - '#FFFFFF'
    - '#725700'
    - '#FC2E8D'
    - '#E6B600'
  brandStrength: 0.2511374051336863
  lightness: 0.13698965481288805
  saturation: 0.3203553657206974
  rhythmicContrast: 0.13620826622148477
title: Motivation & Personal Development
description: motivation. inspiration. development.
author:
  name: Kristoffer Rose Svarre
  url: 'https://www.linkedin.com/in/ksvarre'
  email: ksvarre@gmail.com
navigation:
  - name: Home
    url: 'https://think-like.me'
    type: external
  - name: Technology & Science
    url: 'https://ai.think-like.me'
    type: external
  - name: 'Business, Innovation & Entrepreneurship'
    url: 'https://business.think-like.me'
    type: external
  - name: Crypto Economics & Blockchain Technology
    url: 'https://crypto.think-like.me'
    type: external
  - name: Portfolio & Accomplishments
    url: 'http://portfolio.think-like.me'
    type: external
  - name: About Me
    url: 'https://www.linkedin.com/in/ksvarre'
    type: external
content: []
github: true
