collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.7670251
  brandStrength: 0.1996582
  rhythmicContrast: 0.06451613
  lightness: 0.8172043
typography_spectrum: 1
layout_spectrum: 0.4193548
name: Krsnews
